<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TelemetryCollectorService.Agent-005c781c-6e14-4749-82a2-5fdf3e35a67c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.3.13" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.13" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TelemetryCollectorService.Core\TelemetryCollectorService.Core.csproj" />
  </ItemGroup>
</Project>
